config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :customers do
    resources :users, :only => [:index, :show] do
      resources :scores, :only => [:index, :show], param: :opponent_id
    end
    resources :leagues do
      resources :games
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "leagues#index", customer_id: @customer
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :sport
  belongs_to :customer, class_name: "Customer", foreign_key: 'customer_id'
  has_many :games
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: %i[ show edit update destroy ]
  before_action :set_customer

  # GET /leagues
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  def show
    @league = League.find(params[:id])
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  def create
    @league = League.new(league_params)

    if @league.save
      redirect_to @league, notice: "League was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /leagues/1
  def update
    if @league.update(league_params)
      redirect_to @league, notice: "League was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /leagues/1
  def destroy
    @league.destroy
    redirect_to leagues_url, notice: "League was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    def set_customer
      @customer = current_user.customer
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.fetch(:league, {})
    end
end

app/views/leagues/_form.html.erb
<%= form_with(model: league) do |form| %>
  <% if league.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/_league.html.erb
<div id="<%= dom_id league %>">
</div>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Show this league", @league %> |
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @customer.name %> Leagues</h1><br>

<div id="leagues">
  <% @leagues.each do |league| %>
    <%= render league %>
    <div>
      <p>
        <h2><%= league.name %></h2><br>
        <h4>League Sport: <%= league.sport.sport %></h4><br>
        <%= link_to "Show this league", customer_league_path(@customer, league) %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New league", new_customer_league_path(@customer) %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @league %>

<h2><%= @league.name%></h2><br>
<h4>League Sport: <%= @league.sport.sport %></h4>

<%= link_to "#{@league.name} Games", customer_league_games_path(@customer, @league) %>

<div>
  <%= link_to "Back to leagues", customer_leagues_path(@customer) %>

</div>