config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :customers do
    resources :users, :only => [:index, :show] do
      resources :scores, :only => [:index, :show], param: :opponent_id
    end
    resources :leagues do
      resources :games
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "leagues#index", customer_id: @customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :current_customer

  has_and_belongs_to_many :customers
  has_many :sport_elo_ratings, class_name: 'SportEloRating', foreign_key: 'user_id' do
    def sport(sport_string)
      sport = Sport.find_by(sport: sport_string)
      find_by(sport_id: sport.id)
    end
  end
  has_many :wins, :class_name => 'Game', :foreign_key => 'winner_id'
  has_many :losses, :class_name => 'Game', :foreign_key => 'loser_id'

  validates :first_name, presence: true
  validates :last_name, presence: true

  def formatted_name
    "#{self.first_name} #{self.last_name}" 
  end

  def customer
    @current_customer
  end

  def current_customer_id
    @current_customer.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_variables
  
  def index
    puts current_user.customer
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def set_user_variables
    @customer = current_user.customer
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/index.html.erb
<div class="shadow p-3 mb-5 bg-body rounded content-box">  
  <h1 class="header-border">Users</h1>

  <div class="users">
    <% @users.each do |user| %>
      <h4><%= user.formatted_name %></h4>
      <p><%= user.email %></p>
      <%= link_to "Show this user", customer_user_url(@customer, user) %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.formatted_name %></h1>

<p><%= @user.email %></p>
<!-- Will need to have a drop down for each sport <p><%#= @user.elo_rating %></p> -->
<%= link_to "Show User's Record", customer_user_scores_path(@customer, @user) %><br>
<%= link_to "Back to users", customer_users_path(@customer) %>