config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :customers do
    resources :users, :only => [:index, :show] do
      resources :scores, :only => [:index, :show], param: :opponent_id
    end
    resources :leagues do
      resources :games
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "leagues#index", customer_id: @customer
end

app/models/game.rb
class Game < ApplicationRecord
  validates :winner_id, presence: true
  validates :loser_id, presence: true
  validates :winner_score, presence: true
  validates :loser_score, presence: true
  
  belongs_to :winner, :class_name => "User"
  belongs_to :loser, :class_name => "User"
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :set_user_variables
  before_action :authenticate_user!


  # GET /games
  def index
    @games = Game.where(league_id: @league).order("created_at DESC")
  end

  # GET /games/1
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    respond_to do |format|  
      if @game.save
        winner = User.find(params[:game][:winner_id])
        loser = User.find(params[:game][:loser_id])
        sport = League.find(@game.league_id).sport
        EloService.elo_score_generator(winner, loser, sport)
        format.html { redirect_to customer_league_games_url(@customer, @league), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity}
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to customer_league_games_path(@customer, @league), notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: "Game was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def set_user_variables
      @league = League.find(params[:league_id])
      @customer = current_user.customer
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.fetch(:game, {}).permit(:winner_id, :winner_score, :loser_id, :loser_score, :league_id).with_defaults(league_id: params[:league_id])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: [@customer, @league, game]) do |form| %>
  <div class="mb-3">
    <%= form.label :winner_id, style: "display-block", class: "form-label" %>
    <%= form.collection_select :winner_id, User.order(:first_name), :id, :formatted_name, {include_blank: true}, {class: "form-select"} %>
    <div style="color: red">
      <% if game.errors.include?(:winner_id) %>
        <% game.errors.full_messages_for(:winner_id).each do |error|%>
          <%= error %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :winner_score, style: "display-block", class: "form-label"  %>
    <%= form.text_field :winner_score, class: "form-control" %>
    <div style="color: red">
      <% if game.errors.include?(:winner_score) %>
        <% game.errors.full_messages_for(:winner_score).each do |error|%>
          <%= error %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :loser_id, style: "display-block", class: "form-label"  %>
    <%= form.collection_select :loser_id, User.order(:first_name), :id, :formatted_name, {include_blank: true}, {class: "form-select"} %>
    <div style="color: red">
      <% if game.errors.include?(:loser_id) %>
        <% game.errors.full_messages_for(:loser_id).each do |error|%>
          <%= error %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :loser_score, style: "display-block", class: "form-label"  %>
    <%= form.text_field :loser_score, class: "form-control" %>
    <div style="color: red">
      <% if game.errors.include?(:loser_score) %>
        <% game.errors.full_messages_for(:loser_score).each do |error|%>
          <%= error %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit "Create Game", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
</div>

app/views/games/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/games/edit.html.erb
<%= render "remote_modal", title: "New game" do %>
  
  <%= render "form", game: @game %>

<% end %>

app/views/games/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", game: @game %>
<% end %>

app/views/games/index.html.erb
<div class="shadow p-3 mb-5 bg-body rounded content-box">
  <h1 class="header-border">Games</h1>

  <p style="color: green"><%= notice %></p>

  <% @games.each do |game| %>
    <%= render game %>
      <div class="shadow p-3 mb-5 bg-body rounded game">
        <div class="text">
          <%=link_to "Game ##{game.id}", customer_league_game_path(@customer, @league, game), class: "text-border" %>: <%= game.winner.formatted_name %> has beaten <%= game.loser.formatted_name %> in a set count of <%=game.winner_score.to_s %> to <%=game.loser_score %>
        </div>
      </div>
  <% end %>
</div>

<div class="new-game">
  <div class="shadow p-3 mb-5 bg-body rounded content-box fixed">
    <h5 class="header-border">Just won a game? Log it here!</h5>
    <%= link_to "New game", new_customer_league_game_path(@customer, @league), class: 'btn btn-primary text-border w-100', data: { turbo_frame: "remote_modal" } %>
  </div>
</div>

app/views/games/new.html.erb
<%= render "remote_modal", title: "New game" do %>
  
  <%= render "form", game: @game %>

<% end %>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_customer_league_game_path(@customer, @league, @game) %> |
  <%= link_to "Back to games", customer_league_games_path(@customer, @league) %>

  <%= button_to "Destroy this game", customer_league_games_path(@customer, @league), method: :delete %>
</div>